version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mi-red1

  backend:
    build:
      context: .  # Cambiado de ./proyecto-final a .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - PORT=4000
      - DB_URL=mongodb://mongodb:27017/proyecto
    networks:
      - mi-red1

  frontend:
    build:
      context: ../proyecto-final-frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:4000
    networks:
      - mi-red1

networks:
  mi-red1:
    driver: bridge

volumes:
  mongodb_data: